### ISSUE TITLE
Installing does not install HyperTerm.

### ISSUE THREAD

**Issue by Shugabuga** [lkzhao/hyperterm-alternatescroll#1]
The project won't install into HyperTerm for some reason, even with/without quotation marks.

**Comment by lkzhao** [comment]
Hi @Shugabuga,
this plugin wont work for the current release of hyperterm. You have to wait for 0.7.2+ or clone the hyperterm repo and compile it yourself.

**Comment by Shugabuga** [comment]
Okay, will do!
