### ISSUE TITLE
Custom Scroll Speed

### ISSUE THREAD

**Issue by PernusBernus** [lkzhao/hyperterm-alternatescroll#2]
Been using this on a mbp and finding the scroll speed a little too high. Is it possible to add an option for custom scroll speeds?

Great plugin btw 👍

**Comment by PernusBernus** [comment]
Just had a look at the code, presumably I could just modify these couple of lines to do that?

```javascript
this.props.alternateScrollDown(Math.ceil(-e.wheelDeltaY / 300));
this.props.alternateScrollUp(Math.ceil(e.wheelDeltaY / 300));
```

**Comment by lkzhao** [comment]
I will be pushing an update soon to allow custom scroll speed. :P

And yes, thats where you can tweak the scroll speed if you can't wait.

**Comment by lkzhao** [comment]
@PernusBernus checkout v1.2.0

**Comment by PernusBernus** [comment]
Awesome sauce, now I'm one step closer to replacing iterm2. 😉 Thanks a bunch!
