### ISSUE TITLE
Faster scrolling?

### ISSUE THREAD

**Issue by OmgImAlexis** [lkzhao/hyperterm-alternatescroll#7]
I've tried this out but I've found setting the speed to 100 is still about 1/2 or 1/3 as fast as `terminal.app` is there anyway to set it above 100?

**Comment by patatman** [comment]
You probably need to update your settings, i found a error in the docs.
You need to put the number in quotes, and end the bracket for alternateScroll with a comma.

The correct syntax:
`    // for hyperterm-alternatescroll plugin
    alternateScroll: {
      // 1 to 100 is supported
      scrollSpeed: '90'
    },
`

**Comment by OmgImAlexis** [comment]
That seems to have done it.
